#ifndef SPIRIT_VERSION_H
#define SPIRIT_VERSION_H

#define SPIRIT_VERSION_MAJOR 0
#define SPIRIT_VERSION_MINOR 1
#define SPIRIT_VERSION_PATCH 0

#define SPIRIT_VERSION_STRING "0.1.0"

#endif  //  SPIRIT_VERSION_H
