# サポートしている各種マイコンボードのビルドを行う
#
# ビルドツールは以下の3つで、各種マイコンボードでビルドが通ることを確認する
# - Mbed CLI 1 (mbed)
# - Mbed CLI 2 (mbed-tools)
# - Arduino CLI (arduino-cli)
#
name: Build spirit

on:
  push:
    branches:
      - "main"
    paths:
      - "**/CMakeLists.txt"
      - "**.h"
      - "**.cpp"
      - "**/build.yml"
      - "!tests/**"
  pull_request:
    paths:
      - "**/CMakeLists.txt"
      - "**.h"
      - "**.cpp"
      - "**/build.yml"
      - "!tests/**"
  workflow_dispatch:

jobs:
  build-cli-v1:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F303K8, LPC1768]
        profile: [release, debug, develop]

    steps:
      - uses: actions/checkout@v3

      - name: build-mbed-cli
        run: |
          set -e
          mbed new .
          mbed deploy
          cp spirit/.github/workflows/build-mbed/main.cpp .
          mbed compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}

  build-cli-v2:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F303K8, LPC1768]
        profile: [release, debug, develop]

    steps:
      - uses: actions/checkout@v3

      - name: build-mbed-tools
        run: |
          set -e
          cd ..
          mbed-tools new .
          cp spirit/.github/workflows/build-mbed/main.cpp .
          cp spirit/.github/workflows/build-mbed-tools/CMakeLists.txt .
          mbed-tools deploy
          mbed-tools compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}

  build-arduio-cli:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://dl.espressif.com/dl/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile sketch
        run: |
          cd .github/workflows/build-arduino-cli
          arduino-cli compile --fqbn esp32:esp32:esp32 --library ../../../
