name: Build spirit

on:
  push:
    branches:
      - "main"
    paths:
      - "**/CMakeLists.txt"
      - "**.h"
      - "**.cpp"
      - "**/build.yml"
      - "!tests/**"
  pull_request:
    paths:
      - "**/CMakeLists.txt"
      - "**.h"
      - "**.cpp"
      - "**/build.yml"
      - "!tests/**"
  workflow_dispatch:

jobs:
  build-cli-v1:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F303K8, LPC1768]
        profile: [release, debug, develop]

    steps:
      - uses: actions/checkout@v3

      - name: build-mbed-cli
        run: |
          set -e
          mbed new .
          mbed deploy
          echo "int main(){}">src/main.cpp
          mbed compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}

  build-cli-v2:
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [NUCLEO_F303K8, LPC1768]
        profile: [release, debug, develop]

    steps:
      - uses: actions/checkout@v3

      - name: build-mbed-tools
        run: |
          set -e
          cd ..
          mbed-tools new .
          cp spirit/.github/workflows/build-mbed-tools/CMakeLists.txt CMakeLists.txt
          mbed-tools deploy
          mbed-tools compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}

  build-arduio-cli:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        fqbn: ['esp32:esp32:esp32', 'STMicroelectronics:stm32:GenF3', 'STMicroelectronics:stm32:GenL0']

    steps:
      - uses: actions/checkout@v3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          arduino-cli config init

      - name: Install ESP32 package
        if: matrix.fqbn == 'esp32:esp32:esp32'
        run: |
          arduino-cli config add board_manager.additional_urls https://dl.espressif.com/dl/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install STM32 package
        if: matrix.fqbn != 'esp32:esp32:esp32'
        run: |
          arduino-cli config add board_manager.additional_urls https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
          arduino-cli core update-index
          arduino-cli core install STMicroelectronics:stm32

      - name: Compile sketch
        run: |
          arduino-cli compile --fqbn ${{ matrix.fqbn }} --library . .github/workflows/build-arduino-cli
