name: "Dev Containers"

on:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/**"
  pull_request:
    branches:
      - "main"
    paths:
      - ".devcontainer/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # In runCmd, processing continues except for the last command, even if the exit status is not 0.
            set -e

            # Arduino CLI
            arduino-cli compile --fqbn esp32:esp32:esp32 --library . .github/workflows/build-arduino-cli
            arduino-cli compile --fqbn STMicroelectronics:stm32:GenF3 --library . .github/workflows/build-arduino-cli
            arduino-cli compile --fqbn arduino:mbed:pico --library . .github/workflows/build-arduino-cli

            # Mbed CLI 1
            mkdir /tmp/mbed-cli-1
            cp /workspaces/spirit/.github/workflows/build-mbed/main.cpp /tmp/mbed-cli-1
            cd /tmp/mbed-cli-1
            ln -s /workspaces/spirit
            mbed new .
            mbed deploy
            mbed compile -t GCC_ARM -m NUCLEO_F303K8 --profile release

            # Mbed CLI 2
            mkdir /tmp/mbed-cli-2
            cp /workspaces/spirit/.github/workflows/build-mbed/main.cpp /tmp/mbed-cli-2
            cp /workspaces/spirit/.github/workflows/build-mbed-tools/CMakeLists.txt /tmp/mbed-cli-2
            cd /tmp/mbed-cli-2
            ln -s /workspaces/spirit
            mbed-tools new .
            mbed-tools deploy
            mbed-tools compile -t GCC_ARM -m NUCLEO_F303K8 --profile release
