name: "Dev Containers"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - name: Building image
        run: devcontainer build --workspace-folder .

      - name: Spins up containers
        run: devcontainer up --workspace-folder .

      - name: Build with Arduino CLI
        run: |
          devcontainer exec --workspace-folder . arduino-cli compile --fqbn esp32:esp32:esp32 --library . .github/workflows/build-arduino-cli
          devcontainer exec --workspace-folder . arduino-cli compile --fqbn STMicroelectronics:stm32:GenF3 --library . .github/workflows/build-arduino-cli
          devcontainer exec --workspace-folder . arduino-cli compile --fqbn arduino:mbed:pico --library . .github/workflows/build-arduino-cli

      - name: Build with Mbed CLI 1
        run: |
          devcontainer exec --workspace-folder . mbed new .
          devcontainer exec --workspace-folder . mbed deploy
          devcontainer exec --workspace-folder . cp .github/workflows/build-mbed/main.cpp .
          devcontainer exec --workspace-folder . mbed compile -t GCC_ARM -m NUCLEO_F303K8 --profile release
